name: "Merge to Main"
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
  workflow_dispatch: {}
  pull_request:

env:
  environment: "dev"

jobs:
    upload:
      name: "Upload website assets to S3"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-skip-session-tagging: true
            aws-access-key-id: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
            role-to-assume: ${{ secrets.AWS_GHA_ROLE }}
            role-duration-seconds: 900
            role-session-name: ${{ github.run_id }}-${{ github.run_number }}
            aws-region: eu-west-2

        - name: "Copy to S3"
          id: copy-to-s3
          run: aws s3 sync build s3://burendocom-assets-burendo-${environment} --delete
          working-directory: .
          continue-on-error: false




            
