name: "DEV Upload to S3"
on:
  pull_request:

env:
  environment: "dev"
  role: ${{ secrets.AWS_GHA_ROLE_DEV }}

jobs:
    upload:
      name: "Upload website assets to S3"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-skip-session-tagging: true
            aws-access-key-id: ${{ secrets.ACTIONS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.ACTIONS_SECRET_ACCESS_KEY }}
            role-to-assume: ${role}
            role-duration-seconds: 900
            role-session-name: ${{ github.run_id }}-${{ github.run_number }}
            aws-region: eu-west-2

        - name: "Copy to S3"
          id: copy-to-s3
          run: aws s3 sync . s3://burendocom-assets-burendo-${environment}/website-theme --delete
          working-directory: .
          continue-on-error: false
